# Generated by Django 3.0.6 on 2020-05-17 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '__first__'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message1',
            name='service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.service'),
            preserve_default=False,
        ),
    ]
