# Generated by Django 3.0.6 on 2020-05-17 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message1_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message1',
            name='service',
        ),
    ]
