# Generated by Django 3.0.6 on 2020-05-17 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '__first__'),
        ('chat', '0003_remove_message1_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='message1',
            name='service',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='service_messages', to='main.service'),
            preserve_default=False,
        ),
    ]
