# Generated by Django 2.2 on 2020-05-18 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message1_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message1',
        ),
    ]
