# Generated by Django 2.2 on 2020-05-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message1',
        ),
    ]
