# Generated by Django 2.2 on 2020-05-18 05:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20200513_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='r_number',
            field=models.CharField(default=accounts.models.random_string, max_length=3),
        ),
    ]
