# Generated by Django 2.2 on 2020-05-18 06:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_r_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='r_number',
            new_name='rn1',
        ),
        migrations.AddField(
            model_name='user',
            name='rn2',
            field=models.CharField(default=accounts.models.random_string, max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='rn3',
            field=models.CharField(default=accounts.models.random_string, max_length=3),
        ),
    ]
