# Generated by Django 2.2 on 2020-05-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200518_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rn1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rn2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rn3',
        ),
    ]
