# Generated by Django 3.0.6 on 2020-05-05 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventservice',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='foodservice',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='shopingservice',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='travelservice',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='service',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_main.service_set+', to='contenttypes.ContentType'),
        ),
    ]
