# Generated by Django 3.0.6 on 2020-05-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200505_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='initiator_id',
            new_name='initiator',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_type_id',
            new_name='service_type',
        ),
        migrations.AlterField(
            model_name='service',
            name='service_desc',
            field=models.CharField(max_length=1000),
        ),
    ]
