# Generated by Django 3.0.6 on 2020-05-06 07:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0003_auto_20200506_0621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopingService',
            new_name='ShoppingService',
        ),
    ]
