# Generated by Django 3.0.6 on 2020-05-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200506_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='slackness',
        ),
    ]
