# Generated by Django 3.0.6 on 2020-05-09 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_service_slackness'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.service')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('main.service',),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.RenameField(
            model_name='service_group',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='service_group',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='service_member',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='service_member',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='eventservice',
            name='event_type',
            field=models.CharField(choices=[('Movie', 'Movie'), ('Concert', 'Concert'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='travelservice',
            name='end_point',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='travelservice',
            name='start_point',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
