# Generated by Django 3.0.6 on 2020-05-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200509_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelservice',
            name='end_point',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='travelservice',
            name='start_point',
            field=models.CharField(max_length=1000),
        ),
    ]
